name = "RoweysSACURebalance"
version = 14
copyright = "Rowey"
description = "Mod to alow Balance Team to Easily test the changes due to them being split in to separate PRs"
author = "Rowey"
url = ""
icon = ""
uid = "SCU-v14"
exclusive = false
ui_only = false
conflicts = {}
